### ISSUE TITLE
Entidad Workout no muestra su rutina asociada

### ISSUE THREAD

**Issue by ElenaTomasVela** [ISPP-23-24-Grupo-3/musclemate-backend#103]
# Descripción del problema
Un workout creado no se puede deducir de qué rutina es a partir de la API, ya que durante el listado, la ID de su rutina asociada aparece como nulo.
Adicionalmente, devuelve la ID del cliente 2 veces con el mismo valor, uno como parámetro nombrado `client` y otro como parámetro nombrado `client_id`
![image](https://github.com/ISPP-23-24-Grupo-3/musclemate-backend/assets/73388196/af6007f7-f886-4c7b-bccd-88b93dec9faf)
![image](https://github.com/ISPP-23-24-Grupo-3/musclemate-backend/assets/73388196/5e4ab041-e5dd-40dd-868a-1c3f7be06f2b)

# Pasos para reproducir
1. Poblar la base de datos con los usuarios, owners, gimnasios, clientes y rutinas
2. Crear un workout con cualquier tipo de parámetros, asociado a una rutina.
3. Realizar una petición GET al listado de workouts, `/workouts/`

**Comment by AleSosa13** [comment]
@ElenaTomasVela El problema ya debería estar arreglado

**Comment by AleSosa13** [comment]
> @ElenaTomasVela El problema ya debería estar arreglado

Bueno, todavía no, falta que se mergee la pull request

**Comment by AleSosa13** [comment]
@ElenaTomasVela Ya está arreglado y mergeado
