### ISSUE TITLE
Añadir manera de obtener la ID del rol del usuario

### ISSUE THREAD

**Issue by ElenaTomasVela** [ISPP-23-24-Grupo-3/musclemate-backend#127]
# Descripción
Actualmente, para obtener el usuario logueado, hay que realizar un GET de /users/ y realizar un filtrado para obtener el usuario asociado.
Esto no es viable, especialmente porque requiere que los clientes tengan acceso a dicho listado.

# Propuesta
Dentro del token de autenticación, se puede obtener el nombre de usuario. Se podría añadir que estuviera la ID como Owner, Client, o Gym.
Alternativamente, se podría crear un endpoint (por ejemplo, /users/role/<username>) que devolviera el correspondiente ID.

**Comment by pgmarc** [comment]
# Descripción

Habría que unificar el id de usuario y devolver en el token el username del usuario (Creo que el username es la primary key)

# Propuesta

```python
models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True))
```

Con la restriccion de la primary key ya estaria solucionado

**Comment by davidzarandieta** [comment]
Las url de obtención de detalles de Gym, Clients y Owner se hará con el username de dicha entidad.
