### ISSUE TITLE
Nueva vista Assessment por Client

### ISSUE THREAD

**Issue by lemonada02** [ISPP-23-24-Grupo-3/musclemate-backend#141]
esta nueva vista mostrara si un cliente tiene algun assessment asociado a si mismo y a la maquina seleccionada, esta se podrá editar y en cado de que no exista, se podrá crear

**Comment by agudevbon** [comment]
Se ha creado una vista con dos funcionalidades:
- Para owner y gym -> muestra una lista de todas las valoraciones de esa máquina
- Para client -> muestra la valoracion que hayas hecho de esa maquina
