### ISSUE TITLE
Vista de usuarios no filtra por usuarios del gimansio en el back.

### ISSUE THREAD

**Issue by manortgar** [ISPP-23-24-Grupo-3/musclemate-backend#166]
En la vista /owner/users salen todos los usuarios sin filtrar por el gimnasio del cual pertenece ese owner registrado. Solo tiene que salir los usuarios de ese gimnasio.

**Comment by davidzarandieta** [comment]
Un owner puede tener muchos gimnasios

**Comment by davidzarandieta** [comment]
'clients/<int:gymId>/' esta vista debería hacer lo que pides.
