### ISSUE TITLE
Cliente no puede crear workout

### ISSUE THREAD

**Issue by ElenaTomasVela** [ISPP-23-24-Grupo-3/musclemate-backend#167]
# Descripción
Al intentar crear un workout, la API especifica que es obligatorio proveer una id de cliente. Esto es imposible, ya que los clientes no pueden acceder a su propia id de cliente.

![image](https://github.com/ISPP-23-24-Grupo-3/musclemate-backend/assets/73388196/c8509df4-3b46-49d4-8145-ef42588a35a4)

Este problema parece surgir del Serializer de workouts, que parece seguir creyendo que el campo de cliente es obligatorio a pesar de que se esté obteniendo a partir del usuario realizando la petición. 

# Instrucciones para reproducir
Solo es necesario intentar crear un workout sin proporcionar una id cliente.

**Comment by davidzarandieta** [comment]
Solucionado
