### ISSUE TITLE
Crear list de rutinas por defecto

### ISSUE THREAD

**Issue by Leonidas6000** [ISPP-23-24-Grupo-3/musclemate-backend#255]
Crear un list en la vista de routines que saque las rutinas por defecto para cualquier client de cualquier gimnasio, tambien habra que crear el fixture correspondiente en routine, workout y serie, al menos 2 rutinas por ejemplo espalda y piernas que contengan 3 o 4 workouts con varias series cada uno.

He pensado que una manera de hacerlo seria poniendole un id en concreto a cada routine y luego en el list buscar solo las rutinas con esos ids en concreto y para el id del cliente asociado a las rutinas se puede crear un cliente y un gym y todo lo que haga falta o cambiar el modelo para que no sea necesario añadirle un cliente a la routine

**Comment by manvazmar3** [comment]
Se cierra la tarea de momento porque con el modelo que tenemos no se puede hacer.
