### ISSUE TITLE
Cannot access workouts

### ISSUE THREAD

**Issue by ElenaTomasVela** [ISPP-23-24-Grupo-3/musclemate-backend#83]
# Description
Whenever I try to access the list of workouts from the API or create a workout, I get this screen:
![image](https://github.com/ISPP-23-24-Grupo-3/musclemate-backend/assets/73388196/fbbd73d5-0825-4d58-93cf-41837d775dd3)
# Steps to reproduce
## When fetching the workout list
1. Populate the database with Users, Owners, Gyms, Clients and Routines.
2. Create a workout from the admin panel.
3. Attempt a GET request to /workouts/.
## When creating the workout
1. Write a POST request to /workouts/create/.

**Comment by manortgar** [comment]
@Leonidas6000 Tu que lo dejaste arreglado, puedes mirar que ocurre

![Captura de pantalla 2024-03-07 160400](https://github.com/ISPP-23-24-Grupo-3/musclemate-backend/assets/80253414/0de34b05-c623-4280-a497-cb1966490a01)
