### ISSUE TITLE
Arreglar fallos entidad Ticket

### ISSUE THREAD

**Issue by AMC112002** [ISPP-23-24-Grupo-3/musclemate-backend#86]
Hacen falta crear dos campos nuevos en Ticket y cambiar uno de ellos.

Campos nuevos:

- Fecha: Es importante saber en que fecha se creó el ticket, para diferenciar por la fecha cuando un problema se repita.

- Nombre de usuario: Hace falta saber que usuario ha dejado comentado el Ticket.

Campo a modificar:

- Estado: el estado del Ticket debe ser un boolean, que devuelva resuelto o no resuelto. No puede ser un campo de texto.

PROBLEMA DE POST/CREATE:

Devuelve los datos del cliente como cliente_email y tiene que devolver como cliente: {email: }. Y especificar como hacer el post, porque no se ve claro.

**Comment by AMC112002** [comment]
Correción: el nombre de usuario si es un campo, pero no aparece en la api

**Comment by agudevbon** [comment]
Estaría bien también incluir una fecha en la que se arregla el problema del ticket, se podrían sacar de ahí muchos datos.

¿Os parece bien?  @AMC112002 @davidzarandieta @davdelcar @pgmarc

**Comment by agudevbon** [comment]
Para que quede por escrito el Post /Create de ticket debe realizarse con el siguiente formato de JSON:

{
            "label": "Ticket 1",
            "description": "Description of ticket 1",
            "status": true,
            "date": "2023-12-30",
            "gym": 221987,
            "client": 157856,
            "equipment": 567890
        }
        
Si no se especifica fecha se añadirá la fecha del momento en el que se crea el objeto

**Comment by davdelcar** [comment]
A la hora de asignar el cliente en el Post, teneis que extraerlo del token JWT  que se manda por los headers de la petición, de otra forma, se desconoce el id del cliente

**Comment by angmunpri** [comment]
Es necesario además cambiar el update en ticket ya que al enviar la petición se hace solo mediante id y por tanto se pierde la información del cliente
