### ISSUE TITLE
Requisitos gym

### ISSUE THREAD

**Issue by davidzarandieta** [ISPP-23-24-Grupo-3/musclemate-backend#94]
- [ ] Añadir el enumerado con atributos de Pricing. Standard [Precio] Premium [Precio]
- [x] Un gym solo podrá ser creado, editado y eliminado por un owner.
- [x] Un owner podra listar sus propios gimnasios.

**Comment by AleSosa13** [comment]
Podéis aclararme que significa el primer punto? (Añadir el enumerado con atributos de Pricing. Standard [Precio] Premium [Precio])
