### ISSUE TITLE
Requisitos ticket

### ISSUE THREAD

**Issue by davidzarandieta** [ISPP-23-24-Grupo-3/musclemate-backend#98]
- [x] Una entidad ticket solo podrá ser creada, borrada, actualizada y ver los details por el client que ha hecho el ticket, el owner o el gym asociados a dicho cliente
- [x] La entidad ticket solo podrá ser listada por el gym al que pertenezcan los tickets y su owner
- [x] Se tiene que poder listar los tickets de un cliente y una máquina en concreto
- [x] Solo el cliente, el owner y el gym podrán listar los tickets de ese mismo cliente
- [x] Solo el owner y el gym podrán listar los tickets de una maquina en concreto

**Comment by agudevbon** [comment]
Como funcionalidad adicional, a la hora de listar todos los tickets hay dos opciones.
- Un gym realiza la petición -> se mostrarán únicamente los tickets asociados a ese gym.
- Un owner realiza la petición -> se mostrará una agregación de los tickets asociados a los gimnasios que tengan como dueño al          
owner que ha realizado la petición
